import { useState } from 'react';
import type { ConnectedAPI } from '@midnight-ntwrk/dapp-connector-api';
import type {
  MidnightProviders,
  ProofProvider,
} from '@midnight-ntwrk/midnight-js-types';

import type * as StatProofTypes from '../../contracts/managed/statproof/contract/index.js';
import { describeError } from '../lib/errors';
import { parseThreshold } from '../lib/threshold';

type CircuitCallProps = {
  connected: ConnectedAPI | null;
  proofProvider: ProofProvider | null;
  providers: MidnightProviders | null;
  contractAddress: string;
};

type Status = 'idle' | 'initializing' | 'proving' | 'success' | 'error';

// Demonstration witness: a fixed private value. It is only ever handed to
// the local prover and is never rendered in the UI.
const PRIVATE_VALUE = 85n;
const PRIVATE_STATE_ID = 'statProofPrivateState';

const witnesses: StatProofTypes.Witnesses<{}> = {
  getPrivateValue: () => [{}, PRIVATE_VALUE],
};

export default function CircuitCall({
  connected,
  proofProvider,
  providers,
  contractAddress,
}: CircuitCallProps) {
  const [threshold, setThreshold] = useState('80');
  const [status, setStatus] = useState<Status>('idle');
  const [message, setMessage] = useState<string | null>(null);

  const busy = status === 'initializing' || status === 'proving';

  const handleVerify = async () => {
    if (!connected || !proofProvider || !providers) {
      setStatus('error');
      setMessage('Connect Lace before starting verification.');
      return;
    }

    const numericThreshold = parseThreshold(threshold);

    if (numericThreshold === null) {
      setStatus('error');
      setMessage('Enter a whole number between 0 and 18446744073709551615.');
      return;
    }

    let thresholdPublished = false;

    try {
      setStatus('initializing');
      setMessage(
        'Step 1 of 2 — setting the public threshold. Approve the request in Lace if prompted.',
      );

      const { CompiledContract } = await import(
        '@midnight-ntwrk/midnight-js-protocol/compact-js'
      );

      const { findDeployedContract } = await import(
        '@midnight-ntwrk/midnight-js-contracts'
      );

      const StatProof = await import(
        '../../contracts/managed/statproof/contract/index.js'
      );

      const compiledContract = CompiledContract.make(
        'statproof',
        StatProof.Contract,
      ).pipe(
        CompiledContract.withWitnesses(witnesses),
        CompiledContract.withCompiledFileAssets('/zk'),
      );

      const deployed: any = await findDeployedContract(providers, {
        compiledContract: compiledContract as any,
        contractAddress,
        privateStateId: PRIVATE_STATE_ID,
        initialPrivateState: {},
      });

      await deployed.callTx.initialize(numericThreshold);
      thresholdPublished = true;

      setStatus('proving');
      setMessage(
        'Step 2 of 2 — generating the zero-knowledge proof. This can take a while; keep this tab open.',
      );

      await deployed.callTx.proveThreshold();

      setStatus('success');
      setMessage(
        'Verified on Midnight Preprod. Your private value was never revealed.',
      );
    } catch (error) {
      setStatus('error');
      setMessage(
        describeError(error, 'verify') +
          (thresholdPublished
            ? ' The public threshold was already recorded on-chain.'
            : ''),
      );
    }
  };

  return (
    <section>
      <h2>Private Verification</h2>

      <p>
        Verify that your private value satisfies a public threshold
        without revealing the value.
      </p>

      <label>
        Public threshold
        <input
          type="number"
          min="0"
          step="1"
          value={threshold}
          onChange={(event) => setThreshold(event.target.value)}
          disabled={busy}
        />
      </label>

      <button
        type="button"
        onClick={handleVerify}
        aria-busy={busy}
        disabled={!connected || !proofProvider || !providers || busy}
      >
        {busy && <span className="spinner" aria-hidden="true" />}
        {status === 'initializing'
          ? 'Preparing…'
          : status === 'proving'
            ? 'Generating proof…'
            : 'Verify Privately'}
      </button>

      <p>
        <strong>Private value:</strong> HIDDEN
      </p>

      <p>
        <strong>Privacy:</strong> Proved without revealing your input.
      </p>

      {!connected && (
        <p className="hint">Connect Lace to enable verification.</p>
      )}

      <p className="hint">
        Proofs are generated by a local proof server at http://localhost:6300.
        Start it before verifying (setup steps are in the README).
      </p>

      {message && (
        <div role={status === 'error' ? 'alert' : 'status'}>
          {busy && <span className="spinner" aria-hidden="true" />}
          {message}
        </div>
      )}
    </section>
  );
}
